#+title: abe's literate configuration for GNU Emacs
#+author: abe
#+email: aabm@disroot.org
#+startup: overview
#+property: header-args :mkdirp yes 

* About this Emacs setup

2026 refix edition!

This is my personal configuration file for GNU Emacs. It is written in
a literate style, combining code snippets and documentation in the
same file.

** A literate configuration file

This document serves as the single point of entry into my Emacs setup.
Here all the code is defined and documented, before being extracted
("tangled") out to the Elisp files that are actually loaded by Emacs.

When I want to modify my Emacs setup, I edit this file and then
evaluate the following code block or do =C-c C-v t=. All files are
thus updated accordingly.

#+begin_src emacs-lisp :tangle no :results none
(org-babel-tangle)
#+end_src

This configuration is written in the literate style primarily for
self-clarification. I originally adopted this approach because I used
to share and post bits and pieces of my setup online, and including
documentation was useful for others. I rarely do that nowadays so I
mainly keep this file for myself: I tend to forget exactly how or why
I set something up, so reading back through my own notes is useful in
understanding what is going on in my Emacs.

If you're a stranger reading this, welcome! I hope you get something
useful out of this.

** Use cases for this configuration

Emacs is my general purpose text editor. I use it to read, write and
take notes for both academic and personal purposes. I occasionally use
it for programming. I also use it for all sorts of everyday computing
tasks such as managing files, editing system configs, and reading
email.

** Software and hardware assumptions

I usually run the latest stable build of Emacs available on the Arch
Linux repositories, no compiling Emacs from source. Compatibility with
versions of Emacs other than stable is not accounted for.

I have two computers, both running Arch Linux. One is a reasonably
performant desktop (a so-called "gaming PC"), the other a second-hand
Thinkpad T490. This config is not hardware-dependent at all, as it is
designed to run smoothly across both machines.

On both of these systems, I use a customized but fairly standard
tiling window manager setup. As such, no options specific to desktop
environment suites are provided.

** Licensing 

In line with the GNU philosophy, this configuration is entirely Free
Software. It basically means that you may share and copy the contents
of this file under certain terms. See the [[file:LICENSE][LICENSE]] file in this
repository for more information.

* Initialization and setting up configuration files

What you are now reading is the =config.org= file. It is the document
that generates -- and thus controls -- every other file that underpins
my Emacs configuration.

This org file is not loaded directly. Instead, it is used to produce
the files which contain the actual code. Currently, these files are:

- The standard =early-init.el= :: includes optimisations for starting
  up Emacs and sets some basics in place.
  
- The standard =init.el= :: contains the remainder of the
  configuration.
  
** Headers for init files

Before we get to configuring Emacs, we must produce the init files. I
like to start them off with a header containing license and other
general information.

#+begin_src emacs-lisp :tangle early-init.el
  ;;; early-init.el --- Emacs early configuration file
  ;; Copyright © 2019-2026 abe <aabm@disroot.org>

  ;; Author: abe <aabm@disroot.org>
  ;; Keywords: Emacs configuration, literate programming
  ;; Homepage: https://github.com/neueleninlekture/emacs

  ;;; License:
  ;; This file is NOT part of GNU Emacs.

  ;; This program is free software; you can redistribute it and/or
  ;; modify it under the terms of the GNU General Public License as
  ;; published by the Free Software Foundation; either version 3, or (at
  ;; your option) any later version.

  ;; This program is distributed in the hope that it will be useful, but
  ;; WITHOUT ANY WARRANTY; without even the implied warranty of
  ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ;; General Public License for more details.

  ;; You should have received a copy of the GNU General Public License
  ;; along with GNU Emacs; see the file LICENSE.  If not, you can visit
  ;; https://www.gnu.org/licenses/gpl-3.0.html or write to the Free
  ;; Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  ;; MA 02110-1301, USA.

  ;;; Commentary:
  ;; abe's early-init settings for Emacs. Mainly controls startup. For
  ;; more details, see the config.org file.

#+end_src

#+begin_src emacs-lisp :tangle init.el
  ;;; init.el --- Main Emacs startup file
  ;; Copyright © 2019-2026 abe <aabm@disroot.org>

  ;; Author: abe <aabm@disroot.org>
  ;; Keywords: Emacs configuration, literate programming
  ;; Homepage: https://github.com/neueleninlekture/emacs

  ;;; License:
  ;; This file is NOT part of GNU Emacs.

  ;; This program is free software; you can redistribute it and/or
  ;; modify it under the terms of the GNU General Public License as
  ;; published by the Free Software Foundation; either version 3, or (at
  ;; your option) any later version.

  ;; This program is distributed in the hope that it will be useful, but
  ;; WITHOUT ANY WARRANTY; without even the implied warranty of
  ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ;; General Public License for more details.

  ;; You should have received a copy of the GNU General Public License
  ;; along with GNU Emacs; see the file LICENSE.  If not, you can visit
  ;; https://www.gnu.org/licenses/gpl-3.0.html or write to the Free
  ;; Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  ;; MA 02110-1301, USA.

  ;;; Commentary:
  ;; abe's init settings for Emacs. Contains most configuration options.
  ;; Do not edit this directly. See the config.org file for more
  ;; information.

#+end_src

** Tweaks for faster startup

With some simple tweaking of garbage collection and file settings we
can make Emacs start up faster. We then make it so that these settings
revert back to normal after Emacs has started, as they are not optimal
for continued use, only for startup.

#+begin_src emacs-lisp :tangle early-init.el
  (defvar startup-file-name-handler-alist file-name-handler-alist)

  (setq gc-cons-threshold most-positive-fixnum
	gc-cons-percentage 0.6
	file-name-handler-alist nil)

  (defun startup-reset-defaults ()
    (setq gc-cons-threshold 16777216
	  gc-cons-percentage 0.1
	  file-name-handler-alist startup-file-name-handler-alist))

  (add-hook 'emacs-startup-hook #'startup-reset-defaults)
#+end_src

** Disable =package.el=

We disable =package.el= early, because we do not use it.

#+begin_src emacs-lisp :tangle early-init.el
  (setq package-enable-at-startup nil)
#+end_src

** Tweak UI elements

Here we disable UI elements such as tool and menu bars.

These are settings for how Emacs sets up its frames. We allow more
flexible and less annoying resizing of frames, as well as better frame
titles. We also disable some UI initialization elements like the
default startup screen.

#+begin_src emacs-lisp :tangle early-init.el
  (setq frame-resize-pixelwise t
        frame-inhibit-implied-resize 'force
        frame-title-format '("Emacs: %b")
        ring-bell-function 'ignore
        use-dialog-box nil ; only for mouse events, which I seldom use
        use-file-dialog nil
        inhibit-splash-screen t
        inhibit-startup-screen t
        inhibit-x-resources t
        inhibit-startup-echo-area-message user-login-name ; read the docstring
        inhibit-startup-buffer-menu t)
#+end_src

Next up, we disable the menu, tool and scroll bars. I see little point
in using these.

#+begin_src emacs-lisp :tangle early-init.el
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (tooltip-mode -1)
#+end_src

** Information on startup

This displays a brief message with information on startup time after
Emacs has started.

#+begin_src emacs-lisp :tangle early-init.el
  (add-hook 'emacs-startup-hook
  	    (lambda ()
  	      (message "Welcome, abe! Emacs ready in %s with %d garbage collections."
  		       (format "%.2f seconds"
  			       (float-time
  				(time-subtract
  				 after-init-time
  				 before-init-time)))
  		       gcs-done)))
#+end_src

** Check Emacs version

This snippet checks the currently installed Emacs version and ensures
I am running the intended one. I try to keep this value updated to
whatever version I am currently on.

#+begin_src emacs-lisp :tangle init.el
  ;;; Startup
  ;; Check version
  (when (version< emacs-version "30.2")
    (error "This configuration requires Emacs 30.2 and above!"))
#+end_src

** Load files and directory littering

Here we make sure Emacs is loading the newest file versions and also
not littering our directories with backup and autosave files.

#+begin_src emacs-lisp :tangle init.el
  ;; Load newest file versions
  (setq load-prefer-newer t)

  ;; Reload buffers when their respective files change on disk
  (global-auto-revert-mode t)
  (setq global-auto-revert-non-file-buffers t)

  ;; Do not lock down files
  (setq create-lockfiles nil)

  ;; DO NOT LITTER FOR THE LOVE OF GOD
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+end_src

** Send =custom.el= to the void

By default, Emacs maintains a file called =custom.el=, which contains
settings applied by the user during the execution of Emacs. I never
want this to be a thing, preferring Emacs to exclusively load my
explicitly declared configuration files. Since there is no way to
block Emacs from producing =custom.el= (too many interfaces access and
write to it by default) we thus write it into oblivion. This keeps
configuration clean.

#+begin_src emacs-lisp :tangle init.el
  (setq custom-file "/dev/null") 
#+end_src

** Clear native compilation

Emacs tends to give rather verbose error reports when native-compiling
Elisp. These clog up the ~*Messages*~ buffer and become more annoying
the more packages you have. We thus tell native-compilation to be less
verbose.

#+begin_src emacs-lisp :tangle early-init.el
(when (native-comp-available-p)
  (setq native-comp-async-report-warnings-errors 'silent))
#+end_src

** Enable disabled commands

By default, Emacs hides some commands away from the user. Here we
enable them again.

#+begin_src emacs-lisp :tangle init.el
  (setq disabled-command-function nil)
#+end_src

* Package management

This configuration uses =elpaca= for package management. I use
=elpaca= because I like it's declarative approach to package
management. This means Emacs can only load packages which are
explicitly declared in the config, making it easier to test new
packages without committing to a full install.

I'm sure installing a whole new package manager is far from the
cleanest solution to package management, but it is easy to work with.

** Install =elpaca=

This little script bootstraps =elpaca= by pulling from the official
git repository. This piece of code is the default install method for
=elpaca=, available in its own documentation. It suffers minor changes
occasionally, as the packages gets updated.

#+begin_src emacs-lisp :tangle init.el
  (defvar elpaca-installer-version 0.12)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-sources-directory (expand-file-name "sources/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                :ref nil :depth 1 :inherit ignore
                                :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                :build (:not elpaca-activate)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-sources-directory))
         (build (expand-file-name "elpaca/" elpaca-builds-directory))
         (order (cdr elpaca-order))
         (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (<= emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
          (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                    ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                    ,@(when-let* ((depth (plist-get order :depth)))
                                                        (list (format "--depth=%d" depth) "--no-single-branch"))
                                                    ,(plist-get order :repo) ,repo))))
                    ((zerop (call-process "git" nil buffer t "checkout"
                                          (or (plist-get order :ref) "--"))))
                    (emacs (concat invocation-directory invocation-name))
                    ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                          "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                    ((require 'elpaca))
                    ((elpaca-generate-autoloads "elpaca" repo)))
              (progn (message "%s" (buffer-string)) (kill-buffer buffer))
            (error "%s" (with-current-buffer buffer (buffer-string))))
        ((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
#+end_src

** Enable =use-package=

=use-package= is a useful macro for handling package installation and
loading. We use it for pretty much all of our package management
needs. Since it is now part of Emacs core, we do not have to
explicitly install it, so instead we just tell =elpaca= to enable it.

#+begin_src emacs-lisp :tangle init.el
  (elpaca elpaca-use-package
    (elpaca-use-package-mode))

  (setq use-package-hook-name-suffix nil)
#+end_src

** Manage minor modes with =diminish=

=diminish= allows hiding minor modes from the modeline display. It
also integrates with =use-package=, and can be called from
~use-package~ declarations. We set it up it at this point because it
wil be needed for ~use-package~ declarations ahead.

#+begin_src emacs-lisp :tangle init.el
  (use-package diminish
    :ensure t
    :config
    (diminish 'which-key-mode))
#+end_src

* Keybinding system

=evil-mode= is my primary keybinding system. Basically it provides a
full emulation of Vim keys in Emacs, with added extensibility. I also
use the =general= package for setting up special evil-mode
keybindings.

As is usual in my sorta-annual config refixes though, I have chosen to
temporarily disable =evil-mode= from my config. I can never quite make
up my mind between Vim and Emacs keys. While I like the complex
leader-prefix setup I've come up with here, I have to say I do not
particularly care for Vim editing motions, especially given that I
mostly edit prose and Lisp code, which Emacs does about as well as
Vim, in my opinion. The main reason I keep =evil-mode= around is the
leader-prefix, frankly, which is quite an elegant way to allow for
quick access to packages and utilities in Emacs (see the ever popular
configuration frameworks like Spacemacs or Doom Emacs).

** =evil-mode= and =general.el=

#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-keybinding nil)
    (evil-mode)
    :custom
    (evil-undo-system 'undo-redo)
    :hook
    (with-editor-mode-hook . evil-insert-state))

  (use-package evil-collection
    :ensure t
    :init
    (evil-collection-init))

  (use-package evil-surround
    :ensure t
    :config
    (global-evil-surround-mode t))

  (use-package evil-org
    :ensure t
    :hook
    ((org-mode-hook . evil-org-mode))
    :config
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys))

  (use-package general
    :ensure t
    :init
    (general-evil-setup)
    (general-nmap
     :states 'normal
     :keymaps 'override
     :prefix "SPC"
     :prefix-map 'leader-map
     ;; files
     "ff" 'find-file
     "fd" 'dired
     "fj" 'dired-jump
     "fb" 'consult-bookmark
     ;; dired
     "dd" 'dired-jump
     "df" 'dired
     ;; buffers
     "bb" 'consult-buffer
     "bk" 'kill-this-buffer+
     "bK" 'kill-buffer
     "bi" 'ibuffer
     "bo" 'aabm/other-buffer
     ;; git
     "gg" 'magit-status
     "gc" 'magit-commit-all
     "gp" 'magit-push-current-to-pushremote
     "gs" 'vc-git-log-grep
     ;; search
     "sg" 'consult-grep
     "so" 'consult-outline
     "sm" 'consult-mark
     "ss" 'consult-line
     "sl" 'consult-goto-line
     ;; text editing
     "ti" 'indent-region
     "ty" 'consult-yank-from-kill-ring
     "to" 'olivetti-mode
     "tO" 'olivetti-set-width
     ;; windows
     "wo" 'other-window
     "wd" 'delete-other-windows
     "wk" 'delete-window
     "wj" 'split-window-below-and-switch
     "wl" 'split-window-right-and-switch
     ;; major modes
     "xs" 'eshell
     ;; kill stuff (redundant)
     "kk" 'kill-this-buffer+)

    (general-nmap
     :states 'normal
     :keymaps 'eshell-mode-map
     :prefix ","
     :prefix-map 'local-leader-map
     "y" 'eshell-copy-file-path-at-point
     "f" 'eshell-find-file-at-point
     "o" 'eshell-cat-file-at-point
     "b" 'eshell-put-last-output-to-buffer)

    (general-nmap
     :states 'normal
     :keymaps 'dired-mode-map
     "o" 'dired-xdg-open
     "h" 'dired-hide-details-mode
     "H" 'dired-hide-dotfiles-mode
     "s" 'eshell))
#+end_src

** =which-key=

The =which-key= package uses the minibuffer to display all active
keybindings in the currently typed prefix. It allows you to navigate
your keybindings via prefixes. This is pretty much a basic necessity
for Emacs, especially nice when you forget those cryptically long
keychord sequences.

#+begin_src emacs-lisp :tangle init.el
  (use-package which-key
    :init
    (which-key-mode)
    :custom
    (which-key-idle-delay 0.4))
#+end_src

* Minibuffer

The /minibuffer/ is one of Emacs' most powerful tools. 

** Isearch editing

This package allows one to edit the contents of an =Isearch= as if it
were a normal minibuffer.

#+begin_src emacs-lisp :tangle init.el
  (use-package isearch-mb
    :ensure t
    :diminish isearch-mb-mode
    :init
    (isearch-mb-mode))
#+end_src

** Completion

For minibuffer completion, I use =vertico= along with =orderless=
completion.

#+begin_src emacs-lisp :tangle init.el
  (use-package orderless
    :ensure t)

  (use-package vertico
    :ensure t
    :config
    (vertico-mode)
    :custom
    (completion-styles '(substring orderless))
    (completion-ignore-case t)
    (read-file-name-completion-ignore-case t)
    (read-buffer-completion-ignore-case t)
    (enable-recursive-minibuffers t))

  (use-package consult
    :ensure t)

  (use-package embark
    :ensure t
    :bind
    (("C-," . embark-act))
    :custom
    (embark-action-indicator
     (lambda (map &optional _target)
       (which-key--show-keymap "Embark" map nil nil 'no-paging)
       #'which-key--hide-popup-ignore-command)
     embark-become-indicator embark-action-indicator))

  (use-package embark-consult
    :ensure t)
#+end_src

* Windows and buffers

#+begin_src emacs-lisp :tangle init.el
  (use-package ibuffer
    :bind
    ("C-x C-b" . ibuffer-other-window))

  (defun kill-this-buffer+ ()
    "Kill the current buffer. More reliable alternative to `kill-this-buffer'"
    (interactive)
    (kill-buffer))

  (global-set-key (kbd "M-o") 'other-window)
#+end_src

* Version control

#+begin_src emacs-lisp :tangle init.el
  (use-package transient
    :ensure t)

  (use-package magit
    :ensure t
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1)
    :bind
    ("C-x g" . magit-status))
#+end_src

* Text editing
** Point position

Enabling the following minor modes makes it so that the position of
point is always displayed in the modeline and highlighted in the
buffer. Also enables display of the line numbers on the left side of
the frame.

#+begin_src emacs-lisp :tangle init.el
  (global-hl-line-mode t)
  (line-number-mode t)
  (column-number-mode t)

  (add-hook 'text-mode-hook 'display-line-numbers-mode)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

** Sentence navigation

A nice tweak to sentence navigation commands that makes them more
usable. We change the definition of a sentence to a more reasonable
“something that ends in a single space after punctuation”, instead of
the normal double space. 

#+begin_src emacs-lisp :tangle init.el
  (setq sentence-end-double-space nil)
#+end_src

** Auto-fill text

I like my text to wrap nicely in plain text files. =auto-fill-mode=
does that for me automatically.

#+begin_src emacs-lisp :tangle init.el
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
  (add-hook 'html-mode-hook 'turn-off-auto-fill)
#+end_src

** Handling parens and bracket pairs

The following minor-modes help when dealing with parentheses, quotes
and other paired brackets. =rainbow-delimiters= colors them for
readability of Lisp code. =electric-pair-mode= automatically inserts
pairs when typing. =electric-quote-mode= inserts fancy quotes.

#+begin_src emacs-lisp :tangle init.el
  (use-package rainbow-delimiters
    :ensure t
    :hook
    ((text-mode-hook . rainbow-delimiters-mode)
     (prog-mode-hook . rainbow-delimiters-mode)))

  (setq electric-pair-pairs '((?\{ . ?\})
  			      (?\( . ?\))
  			      (?\[ . ?\])
  			      (?\" . ?\")
  			      (?\“ . ?\”)))
  (electric-pair-mode t)

  (show-paren-mode t)
#+end_src

** Multiple cursors

This handy package allows simultaneous editing of multiple lines. It's
particularly useful for batch-renaming files in Dired.

#+begin_src emacs-lisp :tangle init.el
  (use-package multiple-cursors
    :ensure t)
#+end_src

** Casing and capitalization

Here we replace the normal capitalization functions with their
more flexible useful =dwim= counterparts.

#+begin_src emacs-lisp :tangle init.el
  (global-set-key (kbd "M-c") 'capitalize-dwim)
  (global-set-key (kbd "M-u") 'upcase-dwim)
  (global-set-key (kbd "M-l") 'downcase-dwim)
#+end_src

** Olivetti

=olivetti-mode= is a minor mode which centers text on the screen.

#+begin_src emacs-lisp :tangle init.el
  (use-package olivetti
    :ensure t
    :custom
    (olivetti-body-width 0.6))
#+end_src

* HTML editing

=simple-httpd= allows one to serve a directory as a local webserver.
Useful for editing HTML files and seeing them in the browser.

#+begin_src emacs-lisp :tangle init.el
  (use-package simple-httpd
    :ensure t)
#+end_src
* Org mode
** Editing code blocks

Here we make it so that editing a code block is done in the current
window.

#+begin_src emacs-lisp :tangle init.el
  (setq org-src-window-setup 'current-window)
#+end_src

* File management

** Dired

=dired= is Emacs’ own built-in file manager. It is quite powerful. We
improve its interface and allow it to open files externally.

#+begin_src emacs-lisp :tangle init.el
  (use-package dired
    :config
    (defun dired-xdg-open ()
      "Open the marked files using xdg-open."
      (interactive)
      (let ((file-list (dired-get-marked-files)))
        (mapc
         (lambda (file-path)
    	 (let ((process-connection-type nil))
    	   (start-process "" nil "xdg-open" file-path)))
         file-list)))
    :custom
    (dired-listing-switches "-alh --group-directories-first")
    (dired-dwim-target t)
    (wdired-allow-to-change-permissions t))

  (use-package dired-hide-dotfiles
    :ensure t
    :hook
    (dired-mode-hook . dired-hide-dotfiles-mode)
    :diminish dired-hide-dotfiles-mode
    :bind
    (:map dired-mode-map
  	(("H" . dired-hide-dotfiles-mode))))

  (use-package diredfl
    :ensure t
    :hook
    (dired-mode-hook . diredfl-mode))

#+end_src

** xdg-open

This allows us to open any file from =find-file= externally using =xdg-open=.

#+begin_src emacs-lisp :tangle init.el
  (defun xdg-open (&optional filename)
    (interactive)
    (let ((process-connection-type))
      (start-process
       "" nil (cond ((eq system-type 'gnu/linux) "xdg-open")
                    ((eq system-type 'darwin) "open")
                    ((eq system-type 'windows-nt) "start")
                    (t "")) (expand-file-name
                    (or filename (dired-file-name-at-point))))))

  (defun find-file-auto (orig-fun &rest args)
    (let ((filename (car args)))
      (if (cl-find-if
           (lambda (regexp) (string-match regexp filename))
           '("\\.pdf\\'" "\\.mp4\\'" "\\.wav\\'" "\\.avi\\'" "\\.gif\\'" "\\.docx?\\'" "\\.jpg\\'" "\\.png\\'" "\\.webm\\'" "\\.flac\\'"))
          (xdg-open filename)
        (apply orig-fun args))))

  (advice-add 'find-file :around 'find-file-auto)
#+end_src

* Appearance
** =nerd-icons=

#+begin_src emacs-lisp :tangle init.el
  (use-package nerd-icons
    :ensure t)
#+end_src

** Dashboard

#+begin_src emacs-lisp :tangle init.el
  (use-package dashboard
    :ensure t
    :config
    (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
    (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
    (dashboard-setup-startup-hook)
    :custom
    (dashboard-center-content t)
    (dashboard-vertically-center-content t)
    (dashboard-startup-banner 'logo)
    (dashboard-banner-logo-title "Welcome to GNU Emacs!")
    (dashboard-items '((recents . 5)
  		     (bookmarks . 5)
  		     (projects . 5)))
    (dashboard-startupify-list '(dashboard-insert-banner
                                 dashboard-insert-newline
                                 dashboard-insert-banner-title
                                 dashboard-insert-newline
                                 dashboard-insert-navigator
                                 dashboard-insert-newline))
    (dashboard-navigator-buttons
     `(;; line1
       (("  "
         "Agenda"
         "Open Org agenda"
         (lambda (&rest _) (org-agenda-list))
         'default
         ""
         ""))
       (("  "
         "Config"
         "Open Emacs configuration"
         (lambda (&rest _) (find-file "~/.emacs.d/config.org"))
         'default
         ""
         ""))
       (("  "
         "Mail"
         "Read email in Notmuch"
         (lambda (&rest _) (find-file "~/.emacs.d/emacs.org"))
         'default
         ""
         ""))
       (("  "
         "Notes"
         "Browse org-mode notes"
         (lambda (&rest _) (find-file "~/org"))
         'default
         ""
         ""))
       (("  "
         "Projects"
         "Browse known projects"
         (lambda (&rest _) (project-switch-project))
         'default
         ""
         "")))))
#+end_src

** Theme
Here we set up fonts, themes, and anything visual.

#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'default-frame-alist '(font . "Iosevka Nerd Font 12"))
  (set-frame-font "Iosevka Nerd Font 12" nil t)

  (load-theme 'modus-operandi)

  (set-frame-parameter nil 'alpha-background 100) 
  (add-to-list 'default-frame-alist '(alpha-background . 100))
#+end_src
