#+title: Aabm's literate configuration for GNU Emacs
#+author: aabm
#+email: aabm@disroot.org
#+startup: overview

* About

Yet another complete rewrite!

This is my =personal configuration for GNU Emacs=. It is
structured in a literate style, meaning it includes documentation and
code in the same file.

I use Emacs for lots of things. I write personal notes and documents
with it. I rely on it for my academic work. I read my mail in it. This
configuration sets that all up for me.

In line with the GNU philosophy, this configuration is entirely =free
software=. See the [[*License:~][License]] section in this file for more details.

This configuration is written with a few key guidelines in mind:

- Don't turn Emacs into a complex monstrosity
- When in doubt, always prefer the simpler implementation
- Try the defaults! They're there for a reason!
- Document all config choices!

* License

Copyright © 2019-2022 Aabm <aabm@disroot.org>

Author: Aabm <aabm@disroot.org>

Homepage: https://gitlab.com/aabm/emacs

This file is NOT part of GNU Emacs.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Emacs; see the file LICENSE.  If not, you can visit
https://www.gnu.org/licenses/gpl-3.0.html or write to the Free
Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301, USA.

* Startup
** early-init.el

Here we define all the options to be included in the =early-init.el=
file. This file is loaded very early in the startup process, meaning
it can be used to modify and speed up startup.

*** File header

The license/package header for the =early-init.el= file.

#+begin_src emacs-lisp :tangle early-init.el
  ;;; early-init.el --- Emacs early configuration file
  ;; Copyright © 2019-2022 Aabm <aabm@disroot.org>

  ;; Author: Aabm <aabm@disroot.org>
  ;; Keywords: Emacs configuration, literate programming
  ;; Homepage: https://gitlab.com/aabm/emacs

  ;;; License:
  ;; This file is NOT part of GNU Emacs.

  ;; This program is free software; you can redistribute it and/or
  ;; modify it under the terms of the GNU General Public License as
  ;; published by the Free Software Foundation; either version 3, or (at
  ;; your option) any later version.

  ;; This program is distributed in the hope that it will be useful, but
  ;; WITHOUT ANY WARRANTY; without even the implied warranty of
  ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ;; General Public License for more details.

  ;; You should have received a copy of the GNU General Public License
  ;; along with GNU Emacs; see the file LICENSE.  If not, you can visit
  ;; https://www.gnu.org/licenses/gpl-3.0.html or write to the Free
  ;; Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  ;; MA 02110-1301, USA.

  ;;; Commentary:
  ;; Aabm's early-init settings for Emacs.  This file has been
  ;; automatically generated by `org-babel'. Do not modify it, as your
  ;; changes might be overwritter. Instead, modify the `emacs.org' file.
#+end_src

*** Startup options hack

A fairly simple hack to speed up startup in Emacs. It works by
disabling garbage gollection and the file name handler while Emacs is
starting, and enables them back up once the startup process is
complete.

#+begin_src emacs-lisp :tangle early-init.el
  (defvar startup-file-name-handler-alist file-name-handler-alist)

  (setq gc-cons-threshold most-positive-fixnum
        gc-cons-percentage 0.6
        file-name-handler-alist nil)

  (defun startup-reset-defaults ()
    (setq gc-cons-threshold 16777216
          gc-cons-percentage 0.1
          file-name-handler-alist startup-file-name-handler-alist))

  (add-hook 'emacs-startup-hook #'startup-reset-defaults)
#+end_src

*** Disabling package.el

Here we disable =package.el=, the built-in package manager for
Emacs. We do this for two reasons:

1. it speeds up startup
2. we use a third-party package manager instead

For more on why use a different package management solution, see
below.

#+begin_src emacs-lisp :tangle early-init.el
  (setq package-enable-at-startup nil
        package--init-file-ensured t)
#+end_src

*** Notify startup time

We enable a simple hook to print a message stating startup time and
garbage collection information right after startup. 

#+begin_src emacs-lisp :tangle early-init.el
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs ready in %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract
                                 after-init-time
                                 before-init-time)))
                       gcs-done)))
#+end_src


* Basic appearance

** Font

#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'default-frame-alist '(font . "Iosevka 11"))
#+end_src

** Bars

#+begin_src emacs-lisp :tangle init.el
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Theme

#+begin_src emacs-lisp :tangle init.el
  (load-theme 'modus-vivendi t)
#+end_src

* Quality of life

** Disabling backup files

By default, Emacs litters your directories with backups of files
you edit. I find this behavior not only useless but also irritating.

#+begin_src emacs-lisp :tangle init.el
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+end_src

