#+title: Aabm's literate configuration for GNU Emacs
#+author: aabm
#+email: aabm@disroot.org
#+startup: overview

* About

Yet another complete rewrite!

This is my =personal configuration for GNU Emacs=. It is
structured in a literate style, meaning it includes documentation and
code in the same file.

I use Emacs for lots of things. I write personal notes and documents
with it. I rely on it for my academic work. I read my mail in it. This
configuration sets that all up for me.

In line with the GNU philosophy, this configuration is entirely =free
software=. See the [[*License:~][License]] section in this file for more details.

This configuration is written with a few key guidelines in mind:

- Don't turn Emacs into a complex monstrosity
- When in doubt, always prefer the simpler implementation
- Try the defaults! They're there for a reason!
- Document all config choices!

* License

Copyright © 2019-2022 Aabm <aabm@disroot.org>

Author: Aabm <aabm@disroot.org>

Homepage: https://gitlab.com/aabm/emacs

This file is NOT part of GNU Emacs.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Emacs; see the file LICENSE.  If not, you can visit
https://www.gnu.org/licenses/gpl-3.0.html or write to the Free
Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301, USA.

* Basic appearance

** Font

#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'default-frame-alist '(font . "Iosevka 11"))
#+end_src

** Bars

#+begin_src emacs-lisp :tangle init.el
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Theme

#+begin_src emacs-lisp :tangle init.el
  (load-theme 'modus-vivendi t)
#+end_src

* Quality of life

** Disabling backup files

By default, Emacs litters your directories with backups of files
you edit. I find this behavior not only useless but also irritating.

#+begin_src emacs-lisp :tangle init.el
  (setq make-backup-files nil)
  (setq auto-save-default nil)
#+end_src
