#+title: Aabm's literate configuration for GNU Emacs
#+author: aabm
#+email: aabm@disroot.org
#+seq_todo: TODO(t) | LEGACY(l) DONE(d)
#+startup: overview

* About

This is *Aabm's personal configuration for GNU Emacs.*

The goal of this configuration is to allow the use of Emacs as an
=Integrated Computing Environment=, or a =Virtual Lisp Machine=. This
means Emacs is treated as the primary tool for anything involving the
manipulation of text, and text interfaces are always preferred over
any alternatives.

This configuration covers many use cases. Among these are: writing,
programming, document preparation, reading mail and news feeds, and
much more.

This configuration is organized in a literate style, harnessing the
abilities of =org-mode=. The entire configuration is contained within
the [[file:emacs.org][emacs.org]] file, and all code is extracted (tangled) into the
files which are to be sourced by Emacs.

All package management is handled in a declarative, functional manner,
using =straight.el= as a replacement for the standard
=package.el=. Most configuration is also lazy loaded and contextually
applied with the help of =use-package=.

In line with the Emacs/GNU philosophy, this configuration is entirely
=free software=. See the [[file:LICENSE][LICENSE]] file for more details.
